Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.sudo = "true"
    end
  
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 256
    end
  
    config.vm.define "nfsserver" do |nfsserver|
      nfsserver.vm.network "private_network", ip: "192.168.255.1", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"
      nfsserver.vm.hostname = "nfsserver"
    end
  
    config.vm.define "nfsclient" do |nfsclient|
      nfsclient.vm.network "private_network", ip: "192.168.255.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"      
      nfsclient.vm.hostname = "nfsclient"
    end
  
  end
  
  