Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.network "private_network", ip: "192.168.255.1", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    inetRouter.vm.hostname = "inetRouter"
  end

  config.vm.define "inetRouter2" do |inetRouter2|
    inetRouter2.vm.network "private_network", ip: "192.168.255.6", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"
    inetRouter2.vm.hostname = "inetRouter2"
  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.network "private_network", ip: "192.168.255.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"
    centralRouter.vm.network "private_network", ip: "192.168.255.5", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"
    centralRouter.vm.network "private_network", ip: "192.168.0.1", adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"
    centralRouter.vm.hostname = "centralRouter"
  end

  config.vm.define "centralServer" do |centralServer|
    centralServer.vm.network "private_network", ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dir-net"
    centralServer.vm.hostname = "centralServer"
  end

end

