---
- hosts: nfsserver
  become: true
  tasks:
  - name: Enable ipv4 forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes state=present reload=yes

  - name: restart network
    systemd: name=network state=restarted  

  - name: Enable ipv4 forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes state=present reload=yes

  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
    - bind
    - bind-utils
    - net-tools
    - ntp
    - wget
    - traceroute
    - iptables-services
    - nfs-utils

  - name: enable iptables-services
    systemd: name=iptables enabled=yes

  - name: enable rpcbind
    systemd: name=rpcbind enabled=yes

  - name: enable nfs-server
    systemd: name=nfs-server enabled=yes

  - name: restart rpcbind
    systemd: name=rpcbind state=restarted

  - name: restart nfs-server
    systemd: name=nfs-server state=restarted

  - iptables_raw:
      name: input iptables rules for nfs
      rules: '-A INPUT -p udp -m multiport --dports 111,2049,20048 -m state --state NEW,ESTABLISHED -j ACCEPT'

  - iptables_raw:
      name: input iptables rules for nfs
      rules: '-A OUTPUT -p udp -m multiport --sports 111,2049,20048 -m state --state ESTABLISHED -j ACCEPT'

  - iptables_raw:
      name: input iptables rule for ssh
      rules: '-A INPUT -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT'

  - iptables_raw:
      name: output iptables rule for ssh
      rules: '-A OUTPUT -p tcp --sport 22 -m state --state NEW,ESTABLISHED -j ACCEPT'

  - iptables_raw:
      name: input iptables tcp rule for client
      rules: '-A INPUT -p tcp -s 192.168.255.2 -j ACCEPT'

  - iptables_raw:
      name: output iptables tcp rule for client
      rules: '-A OUTPUT -p tcp -s 192.168.255.2 -j ACCEPT'

  - iptables_raw:
      name: input iptables udp rule for client
      rules: '-A INPUT -p udp -s 192.168.255.2 -j ACCEPT'

  - iptables_raw:
      name: output iptables udp rule for client
      rules: '-A OUTPUT -p udp -s 192.168.255.2 -j ACCEPT'

  - iptables_raw:
      name: drop everything for input
      rules: '-P INPUT DROP'

  - iptables_raw:
      name: drop everything for forward
      rules: '-P FORWARD DROP'     

  - iptables_raw:
      name: drop everything for output
      rules: '-P OUTPUT DROP'  

  - name: restart iptables-services
    systemd: name=iptables state=restarted

  - name: Creates /var/nfs directory
    file:
      path: /var/nfs
      state: directory
      mode: 0444

  - name: Creates /var/nfs/upload directory
    file:
      path: /var/nfs/upload
      state: directory
      mode: 0777

  - name: Modifying /etc/exports 1
    lineinfile: dest=/etc/exports
      line="/var/nfs               192.168.255.0/30(ro,sync,root_squash,all_squash)"    

  - name: Modifying /etc/exports 2
    lineinfile: dest=/etc/exports
      line="/var/nfs/upload        192.168.255.0/30(rw,sync,no_root_squash,no_all_squash)"

  - name: exportfs -r
    command: exportfs -r
    

- hosts: nfsclient
  become: true
  tasks:
  - name: Enable ipv4 forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes state=present reload=yes

  - name: restart network
    systemd: name=network state=restarted  

  - name: Enable ipv4 forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value=1 sysctl_set=yes state=present reload=yes

  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
    - bind
    - bind-utils
    - net-tools
    - ntp
    - wget
    - traceroute
    - iptables-services
    - nfs-utils

  - name: enable rpcbind
    systemd: name=rpcbind enabled=yes

  - name: restart rpcbind
    systemd: name=rpcbind state=restarted

  - name: Creates /var/nfs directory
    file:
      path: /mnt/nfs
      state: directory
      mode: 0775
      recurse: yes

  - name: Creates /mnt/upload directory
    file:
      path: /mnt/upload
      state: directory
      mode: 0775
      recurse: yes

  - name: Modifying /etc/fstab 1
    lineinfile: dest=/etc/fstab
      line="192.168.255.1:/var/nfs /mnt/nfs nfs vers=3,proto=udp,hard,intr,rsize=32768,wsize=32768,noatime 0 0" 

  - name: Modifying /etc/fstab 2
    lineinfile: dest=/etc/fstab         
      line="192.168.255.1:/var/nfs/upload /mnt/upload nfs vers=3,proto=udp,hard,intr,rsize=32768,wsize=32768,noatime 0 0"      

  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
